services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db:/app/db
      - ./backend/chroma_db:/app/chroma_db
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=http://localhost:11434
      - LLAMA_ARG_EMBEDDINGS=true
      - PYTHONPATH=/app:/app/srcs
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    mem_limit: 12gb
    memswap_limit: 16gb
    restart: on-failure

  frontend:
    image: nginx:alpine
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

volumes:
  ollama_models: