version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./rag/db:/app/rag/db
      - ./chroma_db:/app/chroma_db
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434

  frontend:
    image: nginx:debian
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html